---
- name: user-access
  src: https://github.com/cyberrangecz/ansible-role-user-access.git
  scm: git
  version: v1.0.0

- name: disable-qxl
  src: https://github.com/cyberrangecz/ansible-role-disable-qxl.git
  scm: git
  version: v1.0.0
